-- well, i hate everything about all of this.
return {
    CurseAir = "Air",
    CurseWater = "Water",
    CurseFire = "Fire",
    CurseEarth = "Earth",
    CurseAether = "Aether",

    AirNoTooltip = "Air",
    WaterNoTooltip = "Water",
    EarthNoTooltip = "Earth",
    AetherNoTooltip = "Aether",
    FireNoTooltip = "Fire",
    AllElementsBoonHack = "Fire",

    Mixer5CommonIconAlt = "Star Dust",
    PlantFMolyIconAlt = "Moly",
    PlantFNightshadeIconAlt = "Nightshade",
    MetaFabricIcon = "Fate Fabric",
    MetaFabricIconAlt = "Fate Fabric",
    OreFSilverIconAlt = "Silver",
    ReRollAlt = "Change of Fate",
    ExtraChance = "Death Defiance",
    ExtraChanceNoTooltip = "Death Defiance",
    LastStandGiftItem = "Death Defiance",
    PlantGLotusIconAlt = "Lotus",
    RandomLootGiftItem = "Random Boon",
    ReserveManaAlt = "Prime",
    ArmorTotal = "Armor",
    ArmorTotal_NoTooltip = "Armor",
    Mana = "Mana",
    Mana_NoTooltip = "Mana",
    Omega_NoTooltip = "Omega",
    Omega = "Omega",
    PomLevel_NoTooltip = "Pom",
    MoneyDrop = "Money",
    Currency = "Gold",
    Currency_NoTooltip = "Gold",
    HealthRestore = "HoT",
    HealthRestoreAlt = "HoT",
    Hammer = "Daedalus Hammers",
    MetaCardPointsCommonIconAlt = "Ashes",
    MetaCurrencyIcon = "Bones",
    MetaCurrencyIconAlt = "Bones",
    MemPointsCommonIconAlt = "Psyche",
    Health = "Health",
    BloodDropIcon = "Blood Drops",
    HealthUp = "Health",
    HealthUpTotal = "Health",
    EnemyHealth = "Health",
    ManaUp = "Mana",
    SeedMysteryIcon = "Mystery Seed",
    SeedMysteryIconAlt = "Mystery Seed",
    RandomPom = "Random Pom",

    Bullet = "- ",
}
